stages:
  - build

build_app:
  stage: build
  image: node:18
  tags:
    - shared
  script:
    - yarn install
    - yarn build
  artifacts:
    name: "build-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - build/
